server:
  port: ${SERVER_PORT:8000}
logging:
  level:
    ru: DEBUG

keycloak:
  enabled: true

spring:
  neo4j:
    uri: ${DATABASE_URL:bolt://localhost:7687}
    authentication:
      username: ${DATABASE_LOGIN:neo4j}
      password: ${DATABASE_PASSWORD:password}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    topic: ${KAFKA_TOPIC:topic1}
    group-id: ${KAFKA_GROUP:groupId222}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

writeserviceurl: ${DATABASE_WRITE_SERVICE:http://localhost:8080}
tranmanagerserviceurl: ${TRAN_MANAGER_SERVICE:http://localhost:8080}