server:
  port: ${SERVER_PORT:8000}
logging:
  level:
    org.springframework.web: ${WEB_LOGGING_LEVEL:DEBUG}

spring:
  neo4j:
    uri: ${DATABASE_URL:bolt://localhost:7687}
    authentication:
      username: ${DATABASE_LOGIN:neo4j}
      password: ${DATABASE_PASSWORD:password}
