{
 "title": "app_simple_ws_metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "add_new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(ddk_timed_add_new_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.95, rate(ddk_timed_add_new_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.99, rate(ddk_timed_add_new_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "sum(rate(ddk_timed_add_new_seconds_count{status=\"200\"}[1m])) by (status) / 60"
    },
    {
     "expr": "rate(ddk_timed_add_new_seconds_count{status=\"500\"}[5m])"
    }
   ]
  },
  {
   "title": "find_all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(ddk_timed_findall_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.95, rate(ddk_timed_findall_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.99, rate(ddk_timed_findall_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "sum(rate(ddk_timed_findall_seconds_count{status=\"200\"}[1m])) by (status) / 60"
    },
    {
     "expr": "rate(ddk_timed_findall_seconds_count{status=\"500\"}[5m])",
     "legendFormat": "{{error_rate}}"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(nginx_ingress_controller_request_duration_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.95, rate(nginx_ingress_controller_request_duration_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.99, rate(nginx_ingress_controller_request_duration_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=\"200\"}[1m])) by (status) / 60"
    },
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[5m])"
    }
   ]
  },
  {
   "title": "update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(ddk_timed_update_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.95, rate(ddk_timed_update_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.99, rate(ddk_timed_update_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "sum(rate(ddk_timed_update_seconds_count{status=\"200\"}[1m])) by (status) / 60"
    },
    {
     "expr": "rate(ddk_timed_update_seconds_count{status=\"500\"}[5m])",
     "legendFormat": "error_rate"
    }
   ]
  },
  {
   "title": "del",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(ddk_timed_del_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.95, rate(ddk_timed_del_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "quantile(0.99, rate(ddk_timed_del_seconds_sum{status=\"200\"}[5m]))"
    },
    {
     "expr": "sum(rate(ddk_timed_del_seconds_count{status=\"200\"}[1m])) by (status) / 60"
    },
    {
     "expr": "rate(ddk_timed_del_seconds_count{status=\"500\"}[5m])"
    }
   ]
  }
 ]
}