apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ddk
spec:
  type: NodePort
  selector:
    app: app-simple-ws
  ports:
    - port: 80
      targetPort: 8000
      name: http
      protocol: TCP
